apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: mongosvc
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        command:
        - "mongod"
        - "--replSet"
        - "mainReplSet"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 512m
            memory: 512Mi
        volumeMounts:
        - name: mongopvc
          mountPath: "/data/mongo_vol"
  volumeClaimTemplates:
  - metadata:
      name: mongopvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: springapp
        image: shahir5890/springjenkins:15
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: sha
        - name: MONGO_DB_PASSWORD
          value: sha@123
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 112m
            memory: 112Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8080